PY = python

test :
	$(PY) test.py

BuffonsNeedle :
	$(PY) $@.py

MonteHall :
	$(PY) $@.py

ChaosGame :
	$(PY) $@.py

CoinToss :
	$(PY) $@.py

UniformVsNormal :
	$(PY) $@.py

PointsInACircle :
	$(PY) $@.py

Shuffle :
	$(PY) $@.py

clean :
	rm -rf *.bmp *.pyc RNG31Core/*.pyc RNG31Transform/*.pyc  __pycache__/ RNG31Core/__pycache__/ RNG31Transform/__pycache__/
