PY = python

all : test
	echo "Done"

test :
	$(PY) test.py

BuffonsNeedle :
	$(PY) BuffonsNeedle.py

MonteHall :
	$(PY) MonteHall.py

clean :
	rm -rf *.pyc RNG31Core/*.pyc RNG31Transform/*.pyc  __pycache__/ RNG31Core/__pycache__/ RNG31Transform/__pycache__/
