PY = python

test :
	$(PY) test.py

BuffonsNeedle :
	$(PY) BuffonsNeedle.py

MonteHall :
	$(PY) MonteHall.py

ChaosGame :
	$(PY) ChaosGame.py

clean :
	rm -rf *.bmp *.pyc RNG31Core/*.pyc RNG31Transform/*.pyc  __pycache__/ RNG31Core/__pycache__/ RNG31Transform/__pycache__/
